/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Citation { 'source' : string, 'description' : string }
export interface KnowledgeItem {
  'id' : bigint,
  'lawName' : string,
  'description' : string,
  'language' : Language,
  'citation' : Citation,
}
export type Language = { 'en' : null } |
  { 'hi' : null };
export interface LifeGuide {
  'id' : bigint,
  'language' : Language,
  'citation' : Citation,
  'guidance' : string,
  'situation' : string,
}
export interface Message {
  'text' : string,
  'sender' : string,
  'timestamp' : bigint,
}
export interface ProcessStep {
  'id' : bigint,
  'processName' : string,
  'language' : Language,
  'steps' : Array<string>,
  'citation' : Citation,
}
export interface Session {
  'id' : bigint,
  'context' : string,
  'messages' : Array<Message>,
  'createdAt' : bigint,
  'language' : Language,
  'updatedAt' : bigint,
}
export interface _SERVICE {
  'addMessage' : ActorMethod<[bigint, Message], undefined>,
  'createSession' : ActorMethod<[Language, string], bigint>,
  'getAllKnowledgeItems' : ActorMethod<[], Array<KnowledgeItem>>,
  'getAllLifeGuides' : ActorMethod<[], Array<LifeGuide>>,
  'getAllProcessSteps' : ActorMethod<[], Array<ProcessStep>>,
  'getAllSessions' : ActorMethod<[], Array<Session>>,
  'getCapabilities' : ActorMethod<[], string>,
  'getDisclaimer' : ActorMethod<[], string>,
  'getKnowledgeItem' : ActorMethod<[bigint], KnowledgeItem>,
  'getLanguageModules' : ActorMethod<
    [Language],
    [Array<KnowledgeItem>, Array<ProcessStep>, Array<LifeGuide>]
  >,
  'getLifeGuide' : ActorMethod<[bigint], LifeGuide>,
  'getLimitations' : ActorMethod<[], string>,
  'getProcessStep' : ActorMethod<[bigint], ProcessStep>,
  'getSession' : ActorMethod<[bigint], Session>,
  'initialize' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];