/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Language = IDL.Variant({ 'en' : IDL.Null, 'hi' : IDL.Null });
export const Citation = IDL.Record({
  'source' : IDL.Text,
  'description' : IDL.Text,
});
export const KnowledgeItem = IDL.Record({
  'id' : IDL.Nat,
  'lawName' : IDL.Text,
  'description' : IDL.Text,
  'language' : Language,
  'citation' : Citation,
});
export const LifeGuide = IDL.Record({
  'id' : IDL.Nat,
  'language' : Language,
  'citation' : Citation,
  'guidance' : IDL.Text,
  'situation' : IDL.Text,
});
export const ProcessStep = IDL.Record({
  'id' : IDL.Nat,
  'processName' : IDL.Text,
  'language' : Language,
  'steps' : IDL.Vec(IDL.Text),
  'citation' : Citation,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'context' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : IDL.Int,
  'language' : Language,
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Nat, Message], [], []),
  'createSession' : IDL.Func([Language, IDL.Text], [IDL.Nat], []),
  'getAllKnowledgeItems' : IDL.Func([], [IDL.Vec(KnowledgeItem)], ['query']),
  'getAllLifeGuides' : IDL.Func([], [IDL.Vec(LifeGuide)], ['query']),
  'getAllProcessSteps' : IDL.Func([], [IDL.Vec(ProcessStep)], ['query']),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getCapabilities' : IDL.Func([], [IDL.Text], ['query']),
  'getDisclaimer' : IDL.Func([], [IDL.Text], ['query']),
  'getKnowledgeItem' : IDL.Func([IDL.Nat], [KnowledgeItem], ['query']),
  'getLanguageModules' : IDL.Func(
      [Language],
      [IDL.Vec(KnowledgeItem), IDL.Vec(ProcessStep), IDL.Vec(LifeGuide)],
      ['query'],
    ),
  'getLifeGuide' : IDL.Func([IDL.Nat], [LifeGuide], ['query']),
  'getLimitations' : IDL.Func([], [IDL.Text], ['query']),
  'getProcessStep' : IDL.Func([IDL.Nat], [ProcessStep], ['query']),
  'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Language = IDL.Variant({ 'en' : IDL.Null, 'hi' : IDL.Null });
  const Citation = IDL.Record({
    'source' : IDL.Text,
    'description' : IDL.Text,
  });
  const KnowledgeItem = IDL.Record({
    'id' : IDL.Nat,
    'lawName' : IDL.Text,
    'description' : IDL.Text,
    'language' : Language,
    'citation' : Citation,
  });
  const LifeGuide = IDL.Record({
    'id' : IDL.Nat,
    'language' : Language,
    'citation' : Citation,
    'guidance' : IDL.Text,
    'situation' : IDL.Text,
  });
  const ProcessStep = IDL.Record({
    'id' : IDL.Nat,
    'processName' : IDL.Text,
    'language' : Language,
    'steps' : IDL.Vec(IDL.Text),
    'citation' : Citation,
  });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'context' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : IDL.Int,
    'language' : Language,
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Nat, Message], [], []),
    'createSession' : IDL.Func([Language, IDL.Text], [IDL.Nat], []),
    'getAllKnowledgeItems' : IDL.Func([], [IDL.Vec(KnowledgeItem)], ['query']),
    'getAllLifeGuides' : IDL.Func([], [IDL.Vec(LifeGuide)], ['query']),
    'getAllProcessSteps' : IDL.Func([], [IDL.Vec(ProcessStep)], ['query']),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getCapabilities' : IDL.Func([], [IDL.Text], ['query']),
    'getDisclaimer' : IDL.Func([], [IDL.Text], ['query']),
    'getKnowledgeItem' : IDL.Func([IDL.Nat], [KnowledgeItem], ['query']),
    'getLanguageModules' : IDL.Func(
        [Language],
        [IDL.Vec(KnowledgeItem), IDL.Vec(ProcessStep), IDL.Vec(LifeGuide)],
        ['query'],
      ),
    'getLifeGuide' : IDL.Func([IDL.Nat], [LifeGuide], ['query']),
    'getLimitations' : IDL.Func([], [IDL.Text], ['query']),
    'getProcessStep' : IDL.Func([IDL.Nat], [ProcessStep], ['query']),
    'getSession' : IDL.Func([IDL.Nat], [Session], ['query']),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };