/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Session {
    id: bigint;
    context: string;
    messages: Array<Message>;
    createdAt: bigint;
    language: Language;
    updatedAt: bigint;
}
export interface LifeGuide {
    id: bigint;
    language: Language;
    citation: Citation;
    guidance: string;
    situation: string;
}
export interface Citation {
    source: string;
    description: string;
}
export interface Message {
    text: string;
    sender: string;
    timestamp: bigint;
}
export interface ProcessStep {
    id: bigint;
    processName: string;
    language: Language;
    steps: Array<string>;
    citation: Citation;
}
export interface KnowledgeItem {
    id: bigint;
    lawName: string;
    description: string;
    language: Language;
    citation: Citation;
}
export enum Language {
    en = "en",
    hi = "hi"
}
export interface backendInterface {
    addMessage(sessionId: bigint, message: Message): Promise<void>;
    createSession(language: Language, context: string): Promise<bigint>;
    getAllKnowledgeItems(): Promise<Array<KnowledgeItem>>;
    getAllLifeGuides(): Promise<Array<LifeGuide>>;
    getAllProcessSteps(): Promise<Array<ProcessStep>>;
    getAllSessions(): Promise<Array<Session>>;
    getCapabilities(): Promise<string>;
    getDisclaimer(): Promise<string>;
    getKnowledgeItem(id: bigint): Promise<KnowledgeItem>;
    getLanguageModules(language: Language): Promise<[Array<KnowledgeItem>, Array<ProcessStep>, Array<LifeGuide>]>;
    getLifeGuide(id: bigint): Promise<LifeGuide>;
    getLimitations(): Promise<string>;
    getProcessStep(id: bigint): Promise<ProcessStep>;
    getSession(sessionId: bigint): Promise<Session>;
    initialize(): Promise<void>;
}
import type { Citation as _Citation, KnowledgeItem as _KnowledgeItem, Language as _Language, LifeGuide as _LifeGuide, Message as _Message, ProcessStep as _ProcessStep, Session as _Session } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMessage(arg0: bigint, arg1: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0, arg1);
            return result;
        }
    }
    async createSession(arg0: Language, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(to_candid_Language_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(to_candid_Language_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async getAllKnowledgeItems(): Promise<Array<KnowledgeItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllKnowledgeItems();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllKnowledgeItems();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLifeGuides(): Promise<Array<LifeGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLifeGuides();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLifeGuides();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProcessSteps(): Promise<Array<ProcessStep>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProcessSteps();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProcessSteps();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapabilities(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapabilities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapabilities();
            return result;
        }
    }
    async getDisclaimer(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDisclaimer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDisclaimer();
            return result;
        }
    }
    async getKnowledgeItem(arg0: bigint): Promise<KnowledgeItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getKnowledgeItem(arg0);
                return from_candid_KnowledgeItem_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKnowledgeItem(arg0);
            return from_candid_KnowledgeItem_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLanguageModules(arg0: Language): Promise<[Array<KnowledgeItem>, Array<ProcessStep>, Array<LifeGuide>]> {
        if (this.processError) {
            try {
                const result = await this.actor.getLanguageModules(to_candid_Language_n1(this._uploadFile, this._downloadFile, arg0));
                return [
                    from_candid_vec_n3(this._uploadFile, this._downloadFile, result[0]),
                    from_candid_vec_n11(this._uploadFile, this._downloadFile, result[1]),
                    from_candid_vec_n8(this._uploadFile, this._downloadFile, result[2])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLanguageModules(to_candid_Language_n1(this._uploadFile, this._downloadFile, arg0));
            return [
                from_candid_vec_n3(this._uploadFile, this._downloadFile, result[0]),
                from_candid_vec_n11(this._uploadFile, this._downloadFile, result[1]),
                from_candid_vec_n8(this._uploadFile, this._downloadFile, result[2])
            ];
        }
    }
    async getLifeGuide(arg0: bigint): Promise<LifeGuide> {
        if (this.processError) {
            try {
                const result = await this.actor.getLifeGuide(arg0);
                return from_candid_LifeGuide_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLifeGuide(arg0);
            return from_candid_LifeGuide_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLimitations(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLimitations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLimitations();
            return result;
        }
    }
    async getProcessStep(arg0: bigint): Promise<ProcessStep> {
        if (this.processError) {
            try {
                const result = await this.actor.getProcessStep(arg0);
                return from_candid_ProcessStep_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProcessStep(arg0);
            return from_candid_ProcessStep_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: bigint): Promise<Session> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_Session_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_Session_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
}
function from_candid_KnowledgeItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KnowledgeItem): KnowledgeItem {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LifeGuide_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LifeGuide): LifeGuide {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ProcessStep_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessStep): ProcessStep {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    language: _Language;
    citation: _Citation;
    guidance: string;
    situation: string;
}): {
    id: bigint;
    language: Language;
    citation: Citation;
    guidance: string;
    situation: string;
} {
    return {
        id: value.id,
        language: from_candid_Language_n6(_uploadFile, _downloadFile, value.language),
        citation: value.citation,
        guidance: value.guidance,
        situation: value.situation
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    processName: string;
    language: _Language;
    steps: Array<string>;
    citation: _Citation;
}): {
    id: bigint;
    processName: string;
    language: Language;
    steps: Array<string>;
    citation: Citation;
} {
    return {
        id: value.id,
        processName: value.processName,
        language: from_candid_Language_n6(_uploadFile, _downloadFile, value.language),
        steps: value.steps,
        citation: value.citation
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    context: string;
    messages: Array<_Message>;
    createdAt: bigint;
    language: _Language;
    updatedAt: bigint;
}): {
    id: bigint;
    context: string;
    messages: Array<Message>;
    createdAt: bigint;
    language: Language;
    updatedAt: bigint;
} {
    return {
        id: value.id,
        context: value.context,
        messages: value.messages,
        createdAt: value.createdAt,
        language: from_candid_Language_n6(_uploadFile, _downloadFile, value.language),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    lawName: string;
    description: string;
    language: _Language;
    citation: _Citation;
}): {
    id: bigint;
    lawName: string;
    description: string;
    language: Language;
    citation: Citation;
} {
    return {
        id: value.id,
        lawName: value.lawName,
        description: value.description,
        language: from_candid_Language_n6(_uploadFile, _downloadFile, value.language),
        citation: value.citation
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    en: null;
} | {
    hi: null;
}): Language {
    return "en" in value ? Language.en : "hi" in value ? Language.hi : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProcessStep>): Array<ProcessStep> {
    return value.map((x)=>from_candid_ProcessStep_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KnowledgeItem>): Array<KnowledgeItem> {
    return value.map((x)=>from_candid_KnowledgeItem_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LifeGuide>): Array<LifeGuide> {
    return value.map((x)=>from_candid_LifeGuide_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Language_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    en: null;
} | {
    hi: null;
} {
    return value == Language.en ? {
        en: null
    } : value == Language.hi ? {
        hi: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
